config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :pages

  get '/about', from: 'pages#about', to: 'pages#about'
  get '/admin', from: 'pages#admin', to: 'pages#admin'
  get '/admin/product', from: 'pages#product', to: 'pages#product'

  resources :products do
    resources :comments
  end

  get 'cart', to: 'cart#show'
  get 'cart/update_lcd'
  post 'cart/add'
  post 'cart/destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :products,through: :orderables
    
    def total
        orderables.to_a.sum { |orderable| orderable.total}
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :title, presence: true
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  
  def total
    product.disprice.to_i*quantity
  end

end

app/models/product.rb
class Product < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "id", "name", "updated_at"]
      end
      def self.ransackable_associations(auth_object = nil)
        []
    end
    has_one_attached :image
    belongs_to :user
    has_many :comments
    has_many :orderables
    has_many :carts,through: :orderables

    validates :name, presence: true
    validates :disprice, presence: true
    validates :brand, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :comments

  enum role: { admin: 1, customer: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_search

    def set_search
        @q = Product.ransack(params[:q])
    end
    
    before_action :set_render_cart
    before_action :initialize_cart
    before_action :authenticate_user!
    before_action :update_last_seen_at, if: -> { user_signed_in? && (current_user.last_seen_at.nil? || current_user.last_seen_at < 1.minutes.ago)}

    def set_search
        @q = Product.ransack(params[:q])
    end

    def set_render_cart
        @render_cart = true
    end
    def initialize_cart
        @cart ||= Cart.find_by(id: session[:cart_id])
        if @cart.nil?
            @cart = Cart.create
            session[:cart_id] = @cart.id
        end
    end

    def update_last_seen_at
        current_user.update_attribute(:last_seen_at, Time.now)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!

  def show
    @render_cart = true
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)

    if current_orderable && quantity > 0
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
      product_name = @product.name
      product_price = @product.disprice
      update_lcd(product_name, product_price)
      send_serial_command('1')

      redirect_to cart_path, notice: 'Added to cart'
      return
    end
  end

  def destroy
    Orderable.find_by(id: params[:id]).destroy
    redirect_to cart_path, alert: 'Removed From Cart!'
  end

  private

  def update_lcd(name, price)
    serial_port = ::Serial.new('COM3', 9600)
    serial_port.write("#{name} #{price}\n")
    serial_port.close
  end

  def send_serial_command(command)
    port_str = 'COM3'
    baud_rate = 9600

    serial_port = Serial.new(port_str, baud_rate)

    begin
      serial_port.write(command)
    rescue => e
      puts "Error communicating with the serial port: #{e.message}"
    ensure
      serial_port.close
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
    def create
        @product = Product.find_by(id: params[:product_id])
        @comment = @product.comments.create(comments_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to product_path(@product.id),notice: ' Comment Added'
        else
            redirect_to product_path(@product.id),alert: "Comment can't be blank!"
        end
    end

    def destroy
        @product = Product.find_by(id: params[:product_id])
        @comment = @product.comments.find_by(id: params[:id])
        if @comment.destroy
            redirect_to product_path(@product.id),alert: 'Comment Deleted!'
        end
    end

    private
    def comments_params
        params.require(:comment).permit(:title)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :verify_admin, only: [:admin, :product, :destroy]
  def home
  end
  def about
  end

  def admin
    @user = User.all
    @online_user = User.where("last_seen_at > ?", 5.minutes.ago)
  end
  def product
    @product = Product.all
  end

  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
    redirect_to admin_path, alert: "User account deleted successfully."
  end
  private
  def verify_admin
    redirect_to root_path, alert: 'Only admin can authorize this!' unless current_user.admin?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product,only: [:view,:destroy, :show]
    before_action :correct_user,only: [:edit,:update,:destroy]
    def index
        @product = Product.all
        @q = Product.ransack(params[:q])
        @product = @q.result(distinct: true)
    end
    def new
        @product = Product.new
    end
    def create
        @product = Product.create(product_params)
        if @product.save
            redirect_to product_path(@product),notice: 'Product added successfully'
        else
            render :new,status: :bad_request
        end
    end
    def show
        @comment = @product.comments.order('Created_at DESC')
        @product.update(views: @product.views + 1)
    end
    def edit
        @product = Product.find_by(id: params[:id])
    end
    def update
        @product = Product.find_by(id: params[:id])
        if @product.update(product_params)
            redirect_to product_path(@product),notice: 'Product Updated!'
        else
            render :edit,status: :bad_request
        end
    end
    def destroy
        if @product.destroy
            redirect_to root_path,alert: 'Product Deleted!'
        end
    end
    private
    def product_params
        params.require(:product).permit(:name, :oriprice, :disprice, :brand, :category, :image, :user_id)
    end
    def set_product
        @product = Product.find_by(id: params[:id])
    end
    def correct_user
        if current_user.role == 'admin' || current_user.id == @product.user.id
        else
            redirect_to root_path,alert: 'Only admin or post owner can perform this task'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cart/_cart.html.erb
   <% if @cart.orderables.count > 0 %>
   <h3 class="title text-center mt-3 border-bottom p-3 fw-bold"><%= current_user.email.split('@')[0]%>'s Cart</h3>
   <div class="text my-1">
    <%= render 'cart/orderables'%>
      </div>
      <div class="container ">
        </div>
    <% else %>
        <%= render 'cart/emptycart' %>
  <% end %>
<br>

app/views/cart/_emptycart.erb
<div class="py-6 py-lg-12 cart-margin">
        <div class="container">
            <div class="row">
                <div class="offset-lg-3 col-lg-6 col-md-12 col-12 text-center">
                    <img src="../assets/images/bag.svg" alt="" class="img-fluid mb-4">
                    <%= image_tag('img/cart.svg')%>
                    <h2>Your shopping cart is empty</h2>
                    <div>
                        Return to the store to add items for your delivery slot. Before proceed to checkout you must add some products to your shopping cart. You will find a lot of interesting products on our shop page.
                    </div>
                    <a href="/" class="btn btn-primary mt-4">Explore Products</a>
                </div>
            </div>
    </div>
</div>

app/views/cart/_orderables.html.erb
<section class="h-100 gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
        <% @cart.orderables.each do|orderable| %>
        <% product = orderable.product%>
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                  <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                    <% if product.image.attached? %>
                      <%= image_tag(product.image, class: 'w-100 rounded') %>
                      <% else %>
                      <%= image_tag('img/bg.jpg', class: 'w-100 rounded') %>
                    <% end %>
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                    </a>
                  </div>
                </div>
                <div class="col-lg-8 col-md-6 mb-4 mb-lg-0">
                  <p><strong><%= product.name %></strong></p>
                  <p>रू <%= product.disprice %></p>
                  <div class="list-group-item d-flex justify-content-start"">
                  <%= form_with(url: cart_add_path) do |f|%>
                  <%= f.number_field :quantity, value: orderable.quantity,min: 0, class: 'form-control',type: :disabled %>
                  <% end %>
                  <%= form_with(url: cart_destroy_path) do |f|%>
                  <%= f.hidden_field :id, value: orderable.id %>
                  <%= f.button class: 'btn btn-danger mx-1' do%>
                  <i class="fas fa-trash"></i>
                  <% end %>
                  <% end %>
                </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>  
          <div class="card mb-4">
            <div class="card-body">
              <p><strong>Expected shipping delivery</strong></p>
              <p class="mb-0">12.<%=  @cart.orderables.count %>.2023 - 14.<%=  @cart.orderables.count + 1%>.2023</p>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body">
              <p><strong>We accept</strong></p>
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                alt="American Express" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard" />
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Summary</h5>
            </div>
            <div class="card-body">
              <div class="list-group list-group-flush">
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                  Products Quantity
                  <span><%= @cart.orderables.count%></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Shipping Adress
                  <span>Naxal, Kathmandu</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total amount</strong>
                    <strong>
                      <p class="mb-0">(including VAT)</p>
                    </strong>
                  </div>
                  <span><strong>रू<%= @cart.total %></strong></span>
                </li>
              </div>
              <button type="button" class="btnt text-white fw-bold btn-primary btn-block">
                Go to checkout
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>
  

app/views/cart/show.html.erb
<%= render 'cart/cart' if @render_cart%>

app/views/comments/_comment.html.erb
<% if @product.comments.count <= 0%>
<% else %>
  <div class="container d-flex justify-content-center mt-4 mb-100 shadow">
    <div class="row">
        <div class="col-md-12">

            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Recent Reviews</h4>
                    <h6 class="card-subtitle">Latest Reviews by users</h6> </div>
                    <% @comment.each do |x|%>
                    <div class="comment-widgets m-b-20">
                    <div class="d-flex flex-row comment-row">
                        <div class="p-2"><span class="round">
                        <div class="comment-text w-100">
                            <h6><%= x.user.email %>  |   Commented <%= time_ago_in_words(x.created_at) + ' ago'%></h6>
                            <h5><%= x.title %></h5>

                            <p class="m-b-5 m-t-10 text-muted">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it</p>
                        </div>
                        <%= button_to 'Delete', [x.product, x], class: 'btn btn-danger btn-sm ',method: :delete, data: {'turbo-method': :delete}, data: { turbo: "false" } if x.user_id == current_user.id%>
                    </div>
        </div>
            </div>
          <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="container">
    <div class="modal-header p-3 pb-4 border-bottom-0">
        <h4 class="card-title fw-bold">Leave Review</h4>
    </div>
        <%= form_for([@product, @product.comments.build]) do |f| %>
    <div class="modal-body p-3 pt-0">
    <form class="">
        <div class="form-floating mb-3">
        <%= f.text_field :title, class: 'form-control'%> 
        <label for="floatingInput" style="opacity: 0.2;">Commenting as <%= current_user.email%></label>
        </div>
        <%= f.submit  data: { turbo: "false" }, class: ' btn btn-primary '%>
    </form>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag asset_path('img/cart.webp') %>
    <title>GlowCart - RailsxArduino</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Lepcha&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'partials/about' unless params[:controller] == 'pages' && params[:action] == 'about'%>
      <%= render 'partials/navbar' %>
      <%= render 'partials/alert' %>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_features.html.erb
<section class="ftco-section ftco-no-pt ftco-no-pb feature">
    <h1 class="text-center fw-bold">Seamless E-Commerce Experience

    </h1>
    <div class="container">
        <div class="row no-gutters ftco-services">
  <div class="col-lg-4 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
    <div class="media block-6 services p-4 py-md-5">
      <div class="icon d-flex justify-content-center align-items-center mb-4">
       <%= image_tag('img/fs.png', width: '100px') %>
      </div>
      <div class="media-body">
        <h3 class="heading">Free Shipping</h3>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>      
  </div>
  <div class="col-lg-4 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
    <div class="media block-6 services p-4 py-md-5">
      <div class="icon d-flex justify-content-center align-items-center mb-4">
        <%= image_tag('img/cs.png', width: '100px') %>
      </div>
      <div class="media-body">
        <h3 class="heading">Support Customer</h3>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>    
  </div>
  <div class="col-lg-4 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
    <div class="media block-6 services p-4 py-md-5">
      <div class="icon d-flex justify-content-center align-items-center mb-4">
        <%= image_tag('img/sp.png', width: '100px') %>
        </div>
      <div class="media-body">
        <h3 class="heading">Secure Payments</h3>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      </div>
    </div>      
  </div>
</div>
    </div>
</section>

app/views/pages/_getstarted.html.erb
<div class="getstarted ">
    <div class="gs-main">
        <h1>Get started today</h1>
        <p class="text-white">Now that you're all set, it's time to let the GlowCart magic begin! Explore, shop, and experience the joy of technology-infused online shopping like never before.</p>
        <%= link_to 'Get Started', products_path, clasS: "btn-w mt-4 rm"%>
    </div>
    <%= image_tag('img/bg.jpg', class: 'gs-image') %>
</div>

app/views/pages/_joinow.html.erb
<div class="getstarted ">
    <div class="gs-main">
        <h1>Stay Connected</h1>
        <p class="text-white">Join our vibrant community on social media and subscribe to our newsletter to stay updated on the latest trends, special offers, and exciting new additions to the GlowCart universe.</p>
            <input type="text" placeholder="abc@gorails.com">
            <button>Subscribe Now</button>
    </div>
    <%= image_tag('img/bg.jpg', class: 'gs-image') %>
</div>

app/views/pages/_slider.html.erb
<style>
    .logos{
    display: flex;
    overflow: hidden;
    background-color: white;
    }
    .logos-slide{
    white-space: nowrap;
    display: inline-block;
    animation: 5s slide infinite linear;
    }
    .logos-slide img{
    width: 200px; 
    margin: 0px 40px;
    }
    @keyframes slide{
    from{
    transform: translateX(0%);
    } to{
    transform: translateX(-100%);
    }
    }
    .logos:hover .logos-slide{
    animation-play-state: paused;
    }
</style>
<section class="ftco-section ftco-no-pt ftco-no-pb mt-5 p-4">
    <div class="logos">
        <div class="logos-slide">
            <%= image_tag('img/3m.svg')%>
            <%= image_tag('img/barstool-store.svg')%>
            <%= image_tag('img/budweiser.svg')%>
            <%= image_tag('img/buzzfeed.svg')%>
            <%= image_tag('img/forbes.svg')%>
            <%= image_tag('img/macys.svg')%>
            <%= image_tag('img/menshealth.svg')%>
            <%= image_tag('img/mrbeast.svg')%>
        </div>
        <div class="logos-slide">
            <%= image_tag('img/3m.svg')%>
            <%= image_tag('img/barstool-store.svg')%>
            <%= image_tag('img/budweiser.svg')%>
            <%= image_tag('img/buzzfeed.svg')%>
            <%= image_tag('img/forbes.svg')%>
            <%= image_tag('img/macys.svg')%>
            <%= image_tag('img/menshealth.svg')%>
            <%= image_tag('img/mrbeast.svg')%>
        </div>
      </div>
</section>  

app/views/pages/home.html.erb
<section>
<div class="main">
    <h1 class="svg-here">
        <svg aria-hidden="true" viewBox="0 0 418 42" class="main-svg" preserveAspectRatio="none">
            <path d="M203.371.916c-26.013-2.078-76.686 1.963-124.73 9.946L67.3 12.749C35.421 18.062 18.2 21.766 6.004 25.934 1.244 27.561.828 27.778.874 28.61c.07 1.214.828 1.121 9.595-1.176 9.072-2.377 17.15-3.92 39.246-7.496C123.565 7.986 157.869 4.492 195.942 5.046c7.461.108 19.25 1.696 19.17 2.582-.107 1.183-7.874 4.31-25.75 10.366-21.992 7.45-35.43 12.534-36.701 13.884-2.173 2.308-.202 4.407 4.442 4.734 2.654.187 3.263.157 15.593-.78 35.401-2.686 57.944-3.488 88.365-3.143 46.327.526 75.721 2.23 130.788 7.584 19.787 1.924 20.814 1.98 24.557 1.332l.066-.011c1.201-.203 1.53-1.825.399-2.335-2.911-1.31-4.893-1.604-22.048-3.261-57.509-5.556-87.871-7.36-132.059-7.842-23.239-.254-33.617-.116-50.627.674-11.629.54-42.371 2.494-46.696 2.967-2.359.259 8.133-3.625 26.504-9.81 23.239-7.825 27.934-10.149 28.304-14.005.417-4.348-3.529-6-16.878-7.066Z">
            </path>
        </svg>
        Enlightening Shopping 
    </h1>
    <h1>experience with Arduino Integration</h1>
</div>
<div class="main-para">
    <p class="text-center about">Innovative e-commerce web application built using Ruby on Rails. The web app seamlessly integrates with Arduino, allowing it to send signals to the Arduino board whenever a product is added to the cart. </p>
</div>
<div class="main-btn mt-2">
    <%= link_to 'Begin as Customer', products_path, class: 'btn btn-dark'%>
    <%= link_to 'Begin as Seller', new_product_path, class: 'btn btn-outline-dark'%>
</div></section>
<%= render 'pages/getstarted' %>
<%= render 'pages/features' %>
<div class="promo">
    <div class="promo-bg">
        <%= image_tag('img/bg.png', class: 'text-center promo-img')%>
    </div>
</div>

<%= render 'pages/slider'%>
<%= render 'pages/joinow'%>

app/views/partials/_about.html.erb
<div class="news">
    <p>Big news! We're excited to launch CartNotify. <a href="/about">Learn more →</a></p>
</div>

app/views/partials/_navbar.html.erb
<ul style="margin: 0" >
    <div class="logo">
        <%= link_to image_tag('img/logo.png', width: '120px'), root_path %>
    </div>
    <div class="right">
        <li><%= link_to 'Products', products_path, class: 'rm'  if @product != nil?%></li>
        <li><%= link_to 'About', about_path, class: 'rm'%></li>
        <% if user_signed_in? %>
            <% if current_user.admin? %>
                <li><%= link_to 'Admin', admin_path, class: 'rm'%></li>
            <% end %>
            <li><%= link_to  current_user.email, edit_user_registration_path, class: 'rm' %></li>
            <%= link_to cart_path, class: 'position-relative white' do%>
            <i class="fa fa-lg fa-shopping-cart"></i>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                <%= @cart.orderables.count%>
                <span class="visually-hidden">unread messages</span>
              </span>
          <% end %>
            <%= button_to 'Logout',destroy_user_session_path,class:'rm btnt text-white',method: :delete%>
        <% else %>
        <li><%= link_to 'Login', new_user_session_path, class: 'rm'%></li>
        <li><%= link_to 'Signup', new_user_registration_path, class: 'rm'%></li>
        <% end %>
    </div>
</ul>

app/views/products/show.html.erb
<div class="container shadow mt-3">
    <div class="cards ">
        <div class="card-body">
            <h3 class="card-title fw-bold"><%= @product.name %></h3>
            <h6 class="cards-subtitle">Added <%= time_ago_in_words(@product.created_at)+ ' ago'%>  | <%= pluralize(@product.views, 'view') %>  </h6>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6 img-cont">
                    <% if @product.image.attached? %>
                    <div class="white-box text-center"><%= image_tag(@product.image, class:'w-100 rounded')%></div>
                    <% else %>
                    <div class="white-box text-center"><%= image_tag('img/bg.jpg', class:'img-responsive img-thumbnail')%></div>
                    <% end %>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h4 class="box-title mt-5">Product description</h4>
                    <p>Lorem Ipsum available,but the majority have suffered alteration in some form,by injected humour,or randomised words which don't look even slightly believable.but the majority have suffered alteration in some form,by injected humour</p>
                    <h2 class="mt-2">
                        <span class="big">रू <%= @product.disprice%></span><small>
                        <% if @product.oriprice.present? %>
                            <strike>(रू <%= @product.oriprice%>) </strike></small>
                        <% end %>
                    </h2>
                    <div class="input-group mb-2  mt-2  ">
                        <%= form_with(url: cart_add_path, class: 'd-flex') do |f|%>
                        <%= f.hidden_field :id, value: @product.id %>
                        <%= f.number_field :quantity, value: 0,min: 1, class: 'form-control' %>
                        <%= f.submit "Add to cart", class: 'btnt text-white btn-primary mx-1 ',method: :post, data: {'turbo-method': :post}, data: { turbo: "false" }%>
                        <% end %>
                    </div>
                    <% if current_user.id == @product.user.id ||  current_user.role == 'admin' %>
                        <div class="input-flex gap-1">
                            <p><%= link_to products_path, class:'btn btn-primary' do %>
                            <i class="fa fa-lg fa-arrow-left"></i>
                            <% end %></p>
                            <p> <%= link_to edit_product_path(@product), class:'btn btn-primary' do %>
                            <i class="fa fa-lg fa-wrench"></i>
                            <% end %>
                            <%= button_to product_path(@product), method: :delete, class:'btn btn-danger' do%>
                                <i class="fa fa-lg fa-trash"></i>
                            <% end %>
                        </div>
                    <% else %>
                        <div class="input-flex gap-1">
                        <p>
                            <%= link_to products_path, class:'btn btn-primary' do %>
                            <i class="fa fa-lg fa-arrow-left"></i>
                            <% end %>   
                        </p>
                        </div>
                    <%end %>
                    
                    <h3 class="box-title mt-3">Key Highlights</h3>
                    <p>100% Original Products</p>
                    <p>Pay on delivery might be available</p>
                    <p>Easy 14 days returns and exchanges</p>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h3 class="box-title mt-5">General Info</h3>
                    <div class="table-responsive">
                        <table class="table table-striped table-product">
                            <tbody>
                                <tr>
                                    <td width="390">Brand</td>
                                    <% if @product.brand.present? %>
                                        <td><%= @product.brand %></td>
                                        <% else %>
                                        <td>-</td>
                                    <% end %>
                                </tr>
                                <tr>
                                    <td>Original Price</td>
                                    <td><%= @product.oriprice %></td>
                                </tr>
                                <tr>
                                    <td>Discounted Price</td>
                                    <td><%= @product.disprice %></td>
                                </tr>
                                <tr>
                                    <td>Category ID</td>
                                    <td><%= @product.category %></td>
                                </tr>
                                <tr>
                                    <td>Product Code</td>
                                    <td><%= (0...4).map { ('a'..'z').to_a[rand(26)] }.join %>-<%= (0...4).map { ('a'..'z').to_a[rand(26)] }.join %>-<%= @product.id %></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%= render 'comments/form' %>
<%= render 'comments/comment' %>